public class SEUKStaticValues 
{
	public static Integer millisecond_3_day = -3*24*60*60*1000;
    public static Integer millisecond_6_day = -6*24*60*60*1000;
    public static Integer min_Gas_meters = 0;
    public static Integer min_AnnVol_HH = 5000;
    public static Integer min_AnnVol_NHH = 5000;
    public static String Lead_SEUK_B2B_Leads = 'SEUK_B2B_Leads';
    public static String Account_SEUK_B2B_Accounts = 'SEUK_B2B_Accounts';
    public static String Opportunity_StageName = 'Open - not yet priced';
    public static String Opportunity_SEUK_B2B_Opportunity = 'SEUK_B2B_Opportunity';
}