public class UpdateGeo {
    /*
    @InvocableMethod(label='Update Geo')
    public static Void getAccountNames(List<ID> ids) {
        List<String> accountNames = new List<String>();
        Account accounts = [SELECT Id,Name,BillingLongitude,BillingLatitude FROM Account WHERE Id in :ids];
 
            Site__c sitetest = [SELECT Id, Name, Geo__Latitude__s, Geo__Longitude__s, Geo__c FROM Site__c where Id =:accounts.name];
        sitetest.Geo__Latitude__s = accounts.BillingLatitude;
        sitetest.Geo__Longitude__s = accounts.BillingLongitude;
        update sitetest;
        
    }
    */
}